In [ ]:
import pandas as pd
import numpy as np

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
from functools import reduce

In [ ]:
import os

In [ ]:
path = '/content/drive/MyDrive/Job_Recommendation_System'

In [ ]:
os.listdir(path)

['mappings', 'companies', 'jobs']

In [ ]:
import os # Ensure os is imported

csv_files = []
subdirectories = ['mappings', 'companies', 'jobs']

for subdir in subdirectories:
    subdir_path = os.path.join(path,subdir)
    if os.path.isdir(subdir_path):
        for file_name in os.listdir(subdir_path):
            if file_name.endswith('.csv'):
                csv_files.append(os.path.join(subdir_path,file_name))
print("Found CSV files:")
for csv_file in csv_files:
    print(csv_file)

Found CSV files:
/content/drive/MyDrive/Job_Recommendation_System/mappings/industries.csv
/content/drive/MyDrive/Job_Recommendation_System/mappings/skills.csv
/content/drive/MyDrive/Job_Recommendation_System/companies/company_specialities.csv
/content/drive/MyDrive/Job_Recommendation_System/companies/employee_counts.csv
/content/drive/MyDrive/Job_Recommendation_System/companies/company_industries.csv
/content/drive/MyDrive/Job_Recommendation_System/companies/companies.csv
/content/drive/MyDrive/Job_Recommendation_System/jobs/job_industries.csv
/content/drive/MyDrive/Job_Recommendation_System/jobs/job_skills.csv
/content/drive/MyDrive/Job_Recommendation_System/jobs/salaries.csv
/content/drive/MyDrive/Job_Recommendation_System/jobs/benefits.csv

In [ ]:
import pandas as pd
import os # Ensure os is imported for splitext and basename
dataframes = {}
for csv_file in csv_files:
    file_name = os.path.splitext(os.path.basename(csv_file))[0] # Get file name without path and extension
    dataframes[file_name] = pd.read_csv(csv_file)
    print(f"Loaded {file_name}.csv: Shape = {dataframes[file_name].shape}")

# Display the head of one of the DataFrames to verify
if dataframes:
    first_df_name = next(iter(dataframes))
    print(f"\nHead of {first_df_name}:")
    display(dataframes[first_df_name].head())

Loaded industries.csv: Shape = (422, 2)
Loaded skills.csv: Shape = (35, 2)
Loaded company_specialities.csv: Shape = (169387, 2)
Loaded employee_counts.csv: Shape = (35787, 4)
Loaded company_industries.csv: Shape = (24375, 2)
Loaded companies.csv: Shape = (24473, 10)
Loaded job_industries.csv: Shape = (164808, 2)
Loaded job_skills.csv: Shape = (213768, 2)
Loaded salaries.csv: Shape = (40785, 8)
Loaded benefits.csv: Shape = (67943, 3)

Head of industries:

   industry_id                         industry_name
0            1       Defense and Space Manufacturing
1            3       Computer Hardware Manufacturing
2            4                  Software Development
3            5          Computer Networking Products
4            6  Technology, Information and Internet

In [ ]:
for df_name, df_content in dataframes.items():
    print(f"\nHead of {df_name}:")
    display(df_content.head())

Head of industries:

   industry_id                         industry_name
0            1       Defense and Space Manufacturing
1            3       Computer Hardware Manufacturing
2            4                  Software Development
3            5          Computer Networking Products
4            6  Technology, Information and Internet

Head of skills:

  skill_abr          skill_name
0       ART        Art/Creative
1      DSGN              Design
2      ADVR         Advertising
3      PRDM  Product Management
4      DIST        Distribution

Head of company_specialities:

   company_id              speciality
0    22292832      window replacement
1    22292832  patio door replacement
2       20300      Commercial Banking
3       20300          Retail Banking
4       20300                Mortgage

Head of employee_counts:

   company_id  employee_count  follower_count  time_recorded
0      391906             186           32508     1712346173
1    22292832             311            4471     1712346173
2       20300            1053            6554     1712346173
3     3570660             383           35241     1712346173
4      878353              52           26397     1712346173

Head of company_industries:

   company_id                        industry
0      391906  Book and Periodical Publishing
1    22292832                    Construction
2       20300                         Banking
3     3570660  Book and Periodical Publishing
4      878353         Staffing and Recruiting

Head of companies:

,company_id,name,description,company_size,state,country,city,zip_code,address,url
0,1009,IBM,"At IBM, we do more than work. We create. We cr...",7.0,NY,US,"Armonk, New York",10504,International Business Machines Corp.,https://www.linkedin.com/company/ibm
1,1016,GE HealthCare,Every day millions of people feel the impact o...,7.0,0,US,Chicago,0,-,https://www.linkedin.com/company/gehealthcare
2,1025,Hewlett Packard Enterprise,Official LinkedIn of Hewlett Packard Enterpris...,7.0,Texas,US,Houston,77389,1701 E Mossy Oaks Rd Spring,https://www.linkedin.com/company/hewlett-packa...
3,1028,Oracle,We’re a cloud technology company that provides...,7.0,Texas,US,Austin,78741,2300 Oracle Way,https://www.linkedin.com/company/oracle
4,1033,Accenture,Accenture is a leading global professional ser...,7.0,0,IE,Dublin 2,0,Grand Canal Harbour,https://www.linkedin.com/company/accenture

Head of job_industries:

       job_id  industry_id
0  3884428798           82
1  3887473071           48
2  3887465684           41
3  3887467939           82
4  3887467939           80

Head of job_skills:

       job_id skill_abr
0  3884428798      MRKT
1  3884428798        PR
2  3884428798       WRT
3  3887473071      SALE
4  3887465684       FIN

Head of salaries:

,salary_id,job_id,max_salary,med_salary,min_salary,pay_period,currency,compensation_type
0,1,3884428798,NaN,20.0,NaN,HOURLY,USD,BASE_SALARY
1,2,3887470552,25.0,NaN,23.0,HOURLY,USD,BASE_SALARY
2,3,3884431523,120000.0,NaN,100000.0,YEARLY,USD,BASE_SALARY
3,4,3884911725,200000.0,NaN,10000.0,YEARLY,USD,BASE_SALARY
4,5,3887473220,35.0,NaN,33.0,HOURLY,USD,BASE_SALARY

Head of benefits:

       job_id  inferred                     type
0  3887473071         0        Medical insurance
1  3887473071         0         Vision insurance
2  3887473071         0         Dental insurance
3  3887473071         0                   401(k)
4  3887473071         0  Student loan assistance

### Checking Missing Values in all DataFrames

In [ ]:
for df_name, df_content in dataframes.items():
    print(f"\nMissing values in '{df_name}' DataFrame:")
    display(df_content.isnull().sum())

Missing values in 'industries' DataFrame:

industry_id       0
industry_name    34
dtype: int64

Missing values in 'skills' DataFrame:

skill_abr     0
skill_name    0
dtype: int64

Missing values in 'company_specialities' DataFrame:

company_id    0
speciality    0
dtype: int64

Missing values in 'employee_counts' DataFrame:

company_id        0
employee_count    0
follower_count    0
time_recorded     0
dtype: int64

Missing values in 'company_industries' DataFrame:

company_id    0
industry      0
dtype: int64

Missing values in 'companies' DataFrame:

company_id         0
name               1
description      297
company_size    2774
state             22
country            0
city               1
zip_code          28
address           22
url                0
dtype: int64

Missing values in 'job_industries' DataFrame:

job_id         0
industry_id    0
dtype: int64

Missing values in 'job_skills' DataFrame:

job_id       0
skill_abr    0
dtype: int64

Missing values in 'salaries' DataFrame:

salary_id                0
job_id                   0
max_salary            6838
med_salary           33947
min_salary            6838
pay_period               0
currency                 0
compensation_type        0
dtype: int64

Missing values in 'benefits' DataFrame:

job_id      0
inferred    0
type        0
dtype: int64

### Rename DataFrames for Easier Access

In [ ]:
import pandas as pd
# Rename DataFrames for easier access
for df_name, df_content in dataframes.items():
    globals()[f'{df_name}_df'] = df_content
    print(f"DataFrame '{df_name}_df' created successfully.")

print("\nHead of companies_df:")
display(companies_df.head())

DataFrame 'industries_df' created successfully.
DataFrame 'skills_df' created successfully.
DataFrame 'company_specialities_df' created successfully.
DataFrame 'employee_counts_df' created successfully.
DataFrame 'company_industries_df' created successfully.
DataFrame 'companies_df' created successfully.
DataFrame 'job_industries_df' created successfully.
DataFrame 'job_skills_df' created successfully.
DataFrame 'salaries_df' created successfully.
DataFrame 'benefits_df' created successfully.

Head of companies_df:

,company_id,name,description,company_size,state,country,city,zip_code,address,url
0,1009,IBM,"At IBM, we do more than work. We create. We cr...",7.0,NY,US,"Armonk, New York",10504,International Business Machines Corp.,https://www.linkedin.com/company/ibm
1,1016,GE HealthCare,Every day millions of people feel the impact o...,7.0,0,US,Chicago,0,-,https://www.linkedin.com/company/gehealthcare
2,1025,Hewlett Packard Enterprise,Official LinkedIn of Hewlett Packard Enterpris...,7.0,Texas,US,Houston,77389,1701 E Mossy Oaks Rd Spring,https://www.linkedin.com/company/hewlett-packa...
3,1028,Oracle,We’re a cloud technology company that provides...,7.0,Texas,US,Austin,78741,2300 Oracle Way,https://www.linkedin.com/company/oracle
4,1033,Accenture,Accenture is a leading global professional ser...,7.0,0,IE,Dublin 2,0,Grand Canal Harbour,https://www.linkedin.com/company/accenture

In [ ]:
salaries_df.isnull().sum()

salary_id                0
job_id                   0
max_salary            6838
med_salary           33947
min_salary            6838
pay_period               0
currency                 0
compensation_type        0
dtype: int64

In [ ]:
salaries_df.sample(10)

,salary_id,job_id,max_salary,med_salary,min_salary,pay_period,currency,compensation_type
10587,10588,3894562636,25.39,NaN,17.80,HOURLY,USD,BASE_SALARY
21579,21580,3904943418,NaN,20.0,NaN,HOURLY,USD,BASE_SALARY
35415,35416,3902362495,90.00,NaN,50.00,HOURLY,USD,BASE_SALARY
30514,30515,3901981049,118700.00,NaN,100900.00,YEARLY,USD,BASE_SALARY
10581,10582,3894563202,110000.00,NaN,95000.00,YEARLY,USD,BASE_SALARY
34070,34071,3905816672,350000.00,NaN,125000.00,YEARLY,USD,BASE_SALARY
22726,22727,3904953952,NaN,18.0,NaN,HOURLY,USD,BASE_SALARY
30084,30085,3905333649,32.75,NaN,23.25,HOURLY,USD,BASE_SALARY
12222,12223,3898161232,85522.00,NaN,82764.00,YEARLY,USD,BASE_SALARY
20653,20654,3904930430,120000.00,NaN,90000.00,YEARLY,USD,BASE_SALARY

In [ ]:
import pandas as pd
# Fill missing numerical values with the median for relevant columns
for col in ['max_salary', 'med_salary', 'min_salary']:
    if col in salaries_df.columns:
        median_val = salaries_df[col].median()
        # Address FutureWarning by assigning the result back to the column
        salaries_df[col] = salaries_df[col].fillna(median_val)
        print(f"Filled missing values in '{col}' with median: {median_val}")

# Verify that null values have been handled
print("\nMissing values in 'salaries_df' after treatment:")
display(salaries_df.isnull().sum())

Filled missing values in 'max_salary' with median: 85000.0
Filled missing values in 'med_salary' with median: 25.0
Filled missing values in 'min_salary' with median: 62300.0

Missing values in 'salaries_df' after treatment:

salary_id            0
job_id               0
max_salary           0
med_salary           0
min_salary           0
pay_period           0
currency             0
compensation_type    0
dtype: int64

In [ ]:
companies_df.isnull().sum()

company_id         0
name               1
description      297
company_size    2774
state             22
country            0
city               1
zip_code          28
address           22
url                0
dtype: int64

In [ ]:
industries_df.isnull().sum()

industry_id       0
industry_name    34
dtype: int64

In [ ]:
companies_df.sample()

,company_id,name,description,company_size,state,country,city,zip_code,address,url
24297,101802124,Law Office of Chen & Associates Inc. 恒莹律师事务所,Expert Legal Services\nSeeking legal advice ca...,NaN,Pennsylvania,US,Philadelphia,19152,8304A Bustleton Ave,https://www.linkedin.com/company/law-office-of...

In [ ]:
companies_df.isnull().sum()

company_id         0
name               1
description      297
company_size    2774
state             22
country            0
city               1
zip_code          28
address           22
url                0
dtype: int64

In [ ]:
companies_df['city'].value_counts()

city
New York          1185
0                 1004
Chicago            502
San Francisco      424
Houston            421
                  ...
Graham               1
Saint Joseph         1
Citrus Heights       1
Post Falls           1
Port Arthur          1
Name: count, Length: 4124, dtype: int64

### Handling Missing Values in `companies_df`

In [ ]:
import pandas as pd
# Drop rows where 'name' is null, as it's a critical identifier and only 1 value is missing
companies_df.dropna(subset=['name'], inplace=True);
print("Dropped rows with missing 'name' values.")

# Fill 'description' and 'address' missing values with an empty string
companies_df['description'] = companies_df['description'].fillna('');
companies_df['address'] = companies_df['address'].fillna('');
print("Filled missing 'description' and 'address' with empty strings.")

# For categorical/discrete columns, fill missing values with the mode
for col in ['company_size', 'state', 'city', 'zip_code']:
    if col in companies_df.columns:
        mode_val = companies_df[col].mode()[0] # .mode() can return multiple values, so take the first
        companies_df[col] = companies_df[col].fillna(mode_val);
        print(f"Filled missing values in '{col}' with mode: {mode_val}")

# Verify that null values have been handled in companies_df
print("\nMissing values in 'companies_df' after treatment:")
display(companies_df.isnull().sum())

Dropped rows with missing 'name' values.
Filled missing 'description' and 'address' with empty strings.
Filled missing values in 'company_size' with mode: 2.0
Filled missing values in 'state' with mode: 0
Filled missing values in 'city' with mode: New York
Filled missing values in 'zip_code' with mode: 0

Missing values in 'companies_df' after treatment:

company_id      0
name            0
description     0
company_size    0
state           0
country         0
city            0
zip_code        0
address         0
url             0
dtype: int64

### Handling Missing Values in `industries_df`

In [ ]:
import pandas as pd
# Fill missing 'industry_name' values with a placeholder like 'Unknown'
industries_df['industry_name'] = industries_df['industry_name'].fillna('Unknown')
print("Filled missing 'industry_name' with 'Unknown'.")

# Verify that null values have been handled in industries_df
print("\nMissing values in 'industries_df' after treatment:")
display(industries_df.isnull().sum())

Filled missing 'industry_name' with 'Unknown'.

Missing values in 'industries_df' after treatment:

industry_id      0
industry_name    0
dtype: int64

### Inspecting other DataFrames for Missing Values

Now, let's quickly check the remaining dataframes to ensure there are no other significant missing values that need immediate attention before we proceed with merging.

In [ ]:
for df_name, df_content in dataframes.items():
    # Skip dataframes we've already processed or will process differently
    if df_name in ['salaries', 'companies', 'industries']:
        continue

    print(f"\nMissing values in '{df_name}_df' DataFrame:")
    missing_counts = df_content.isnull().sum()
    if missing_counts.sum() == 0:
        print("No missing values.")
    else:
        display(missing_counts)

Missing values in 'skills_df' DataFrame:
No missing values.

Missing values in 'company_specialities_df' DataFrame:
No missing values.

Missing values in 'employee_counts_df' DataFrame:
No missing values.

Missing values in 'company_industries_df' DataFrame:
No missing values.

Missing values in 'job_industries_df' DataFrame:
No missing values.

Missing values in 'job_skills_df' DataFrame:
No missing values.

Missing values in 'benefits_df' DataFrame:
No missing values.

## Data Integration: Merging DataFrames

### Merging `job_industries_df` with `industries_df`

In [ ]:
import pandas as pd
job_industries_merged_df = pd.merge(job_industries_df, industries_df, on='industry_id', how='left')
print("Shape of job_industries_merged_df:", job_industries_merged_df.shape)
display(job_industries_merged_df.head())

Shape of job_industries_merged_df: (164808, 3)

       job_id  industry_id                   industry_name
0  3884428798           82  Book and Periodical Publishing
1  3887473071           48                    Construction
2  3887465684           41                         Banking
3  3887467939           82  Book and Periodical Publishing
4  3887467939           80            Advertising Services

### Merging `job_skills_df` with `skills_df`

In [ ]:
import pandas as pd
job_skills_merged_df = pd.merge(job_skills_df, skills_df, on='skill_abr', how='left')
print("Shape of job_skills_merged_df:", job_skills_merged_df.shape)
display(job_skills_merged_df.head())

Shape of job_skills_merged_df: (213768, 3)

       job_id skill_abr        skill_name
0  3884428798      MRKT         Marketing
1  3884428798        PR  Public Relations
2  3884428798       WRT   Writing/Editing
3  3887473071      SALE             Sales
4  3887465684       FIN           Finance

### Consolidating Job Information: Aggregating Industries and Skills

In [ ]:
import pandas as pd
# Aggregate industry names for each job_id into a list
job_industries_agg = job_industries_merged_df.groupby('job_id')['industry_name'].apply(list).reset_index()
job_industries_agg.rename(columns={'industry_name': 'industries'}, inplace=True)
print("Shape of aggregated job industries:", job_industries_agg.shape)
display(job_industries_agg.head())

# Aggregate skill names for each job_id into a list
job_skills_agg = job_skills_merged_df.groupby('job_id')['skill_name'].apply(list).reset_index()
job_skills_agg.rename(columns={'skill_name': 'skills'}, inplace=True)
print("\nShape of aggregated job skills:", job_skills_agg.shape)
display(job_skills_agg.head())

Shape of aggregated job industries: (127125, 2)

     job_id                   industries
0    921716                [Real Estate]
1   1218575  [Hospitals and Health Care]
2   2264355     [Religious Institutions]
3   9615617     [Beverage Manufacturing]
4  10998357                [Restaurants]

Shape of aggregated job skills: (126807, 2)

     job_id                                          skills
0    921716                              [Marketing, Sales]
1   1218575                          [Health Care Provider]
2   1829192                          [Health Care Provider]
3   2264355  [Design, Art/Creative, Information Technology]
4  10998357                     [Management, Manufacturing]

### Creating a Base Job DataFrame and Merging Aggregated Data

In [ ]:
import pandas as pd
# Get all unique job_ids from relevant dataframes
unique_job_ids = pd.concat([salaries_df['job_id'], benefits_df['job_id'], job_industries_df['job_id'], job_skills_df['job_id']]).unique()
jobs_df = pd.DataFrame({'job_id': unique_job_ids})
print("Shape of initial jobs_df with unique job IDs:", jobs_df.shape)
display(jobs_df.head())

# Merge aggregated industries
jobs_df = pd.merge(jobs_df, job_industries_agg, on='job_id', how='left')
print("\nShape after merging industries:", jobs_df.shape)

# Merge aggregated skills
jobs_df = pd.merge(jobs_df, job_skills_agg, on='job_id', how='left')
print("Shape after merging skills:", jobs_df.shape)
display(jobs_df.head())

# Fill NaN for industries and skills with empty lists for easier processing later
jobs_df['industries'] = jobs_df['industries'].apply(lambda x: x if isinstance(x, list) else [])
jobs_df['skills'] = jobs_df['skills'].apply(lambda x: x if isinstance(x, list) else [])
print("\nUpdated jobs_df with empty lists for missing industries/skills.")
display(jobs_df.head())
# Ensure jobs_df is defined for subsequent steps.

Shape of initial jobs_df with unique job IDs: (128427, 1)

       job_id
0  3884428798
1  3887470552
2  3884431523
3  3884911725
4  3887473220

Shape after merging industries: (128427, 2)
Shape after merging skills: (128427, 3)

,job_id,industries,skills
0,3884428798,[Book and Periodical Publishing],"[Marketing, Public Relations, Writing/Editing]"
1,3887470552,[Chemical Manufacturing],[Administrative]
2,3884431523,[Mining],"[Management, Training]"
3,3884911725,"[Biotechnology Research, Medical Equipment Man...","[General Business, Business Development, Sales]"
4,3887473220,[Financial Services],[Project Management]

Updated jobs_df with empty lists for missing industries/skills.

,job_id,industries,skills
0,3884428798,[Book and Periodical Publishing],"[Marketing, Public Relations, Writing/Editing]"
1,3887470552,[Chemical Manufacturing],[Administrative]
2,3884431523,[Mining],"[Management, Training]"
3,3884911725,"[Biotechnology Research, Medical Equipment Man...","[General Business, Business Development, Sales]"
4,3887473220,[Financial Services],[Project Management]

### Merging Salaries and Benefits into the Job DataFrame

In [ ]:
import pandas as pd
# Merge salaries_df
jobs_df = pd.merge(jobs_df, salaries_df.drop(columns=['salary_id']), on='job_id', how='left')
print("Shape after merging salaries:", jobs_df.shape)
display(jobs_df.head())

# Merge benefits_df (aggregate benefits first as a job can have multiple benefits)
job_benefits_agg = benefits_df.groupby('job_id')['type'].apply(list).reset_index()
job_benefits_agg.rename(columns={'type': 'benefits'}, inplace=True)
jobs_df = pd.merge(jobs_df, job_benefits_agg, on='job_id', how='left')
print("Shape after merging benefits:", jobs_df.shape)
display(jobs_df.head())

# Fill NaN for benefits with empty lists
jobs_df['benefits'] = jobs_df['benefits'].apply(lambda x: x if isinstance(x, list) else [])
print("\nFinal jobs_df with all job-related information:")
display(jobs_df.head())
print("Final jobs_df info:")
jobs_df.info()
# Ensure jobs_df is fully processed before final merge.

Shape after merging salaries: (128427, 9)

,job_id,industries,skills,max_salary,med_salary,min_salary,pay_period,currency,compensation_type
0,3884428798,[Book and Periodical Publishing],"[Marketing, Public Relations, Writing/Editing]",85000.0,20.0,62300.0,HOURLY,USD,BASE_SALARY
1,3887470552,[Chemical Manufacturing],[Administrative],25.0,25.0,23.0,HOURLY,USD,BASE_SALARY
2,3884431523,[Mining],"[Management, Training]",120000.0,25.0,100000.0,YEARLY,USD,BASE_SALARY
3,3884911725,"[Biotechnology Research, Medical Equipment Man...","[General Business, Business Development, Sales]",200000.0,25.0,10000.0,YEARLY,USD,BASE_SALARY
4,3887473220,[Financial Services],[Project Management],35.0,25.0,33.0,HOURLY,USD,BASE_SALARY

Shape after merging benefits: (128427, 10)

,job_id,industries,skills,max_salary,med_salary,min_salary,pay_period,currency,compensation_type,benefits
0,3884428798,[Book and Periodical Publishing],"[Marketing, Public Relations, Writing/Editing]",85000.0,20.0,62300.0,HOURLY,USD,BASE_SALARY,NaN
1,3887470552,[Chemical Manufacturing],[Administrative],25.0,25.0,23.0,HOURLY,USD,BASE_SALARY,NaN
2,3884431523,[Mining],"[Management, Training]",120000.0,25.0,100000.0,YEARLY,USD,BASE_SALARY,"[Medical insurance, Vision insurance, Dental i..."
3,3884911725,"[Biotechnology Research, Medical Equipment Man...","[General Business, Business Development, Sales]",200000.0,25.0,10000.0,YEARLY,USD,BASE_SALARY,NaN
4,3887473220,[Financial Services],[Project Management],35.0,25.0,33.0,HOURLY,USD,BASE_SALARY,NaN

Final jobs_df with all job-related information:

,job_id,industries,skills,max_salary,med_salary,min_salary,pay_period,currency,compensation_type,benefits
0,3884428798,[Book and Periodical Publishing],"[Marketing, Public Relations, Writing/Editing]",85000.0,20.0,62300.0,HOURLY,USD,BASE_SALARY,[]
1,3887470552,[Chemical Manufacturing],[Administrative],25.0,25.0,23.0,HOURLY,USD,BASE_SALARY,[]
2,3884431523,[Mining],"[Management, Training]",120000.0,25.0,100000.0,YEARLY,USD,BASE_SALARY,"[Medical insurance, Vision insurance, Dental i..."
3,3884911725,"[Biotechnology Research, Medical Equipment Man...","[General Business, Business Development, Sales]",200000.0,25.0,10000.0,YEARLY,USD,BASE_SALARY,[]
4,3887473220,[Financial Services],[Project Management],35.0,25.0,33.0,HOURLY,USD,BASE_SALARY,[]

Final jobs_df info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 128427 entries, 0 to 128426
Data columns (total 10 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   job_id             128427 non-null  int64
 1   industries         128427 non-null  object
 2   skills             128427 non-null  object
 3   max_salary         40785 non-null   float64
 4   med_salary         40785 non-null   float64
 5   min_salary         40785 non-null   float64
 6   pay_period         40785 non-null   object
 7   currency           40785 non-null   object
 8   compensation_type  40785 non-null   object
 9   benefits           128427 non-null  object
dtypes: float64(3), int64(1), object(6)
memory usage: 9.8+ MB

In [ ]:
import pandas as pd
# Aggregate company industries for each company_id into a list
company_industries_agg = company_industries_df.groupby('company_id')['industry'].apply(list).reset_index()
company_industries_agg.rename(columns={'industry': 'company_industries'}, inplace=True)
print("Shape of aggregated company industries:", company_industries_agg.shape)
display(company_industries_agg.head())

# Aggregate company specialities for each company_id into a list
company_specialities_agg = company_specialities_df.groupby('company_id')['speciality'].apply(list).reset_index()
company_specialities_agg.rename(columns={'speciality': 'company_specialities'}, inplace=True);
print("\nShape of aggregated company specialities:", company_specialities_agg.shape)
display(company_specialities_agg.head())

Shape of aggregated company industries: (24365, 2)

   company_id                  company_industries
0        1009     [IT Services and IT Consulting]
1        1016         [Hospitals and Health Care]
2        1025     [IT Services and IT Consulting]
3        1028     [IT Services and IT Consulting]
4        1033  [Business Consulting and Services]

Shape of aggregated company specialities: (17780, 2)

   company_id                               company_specialities
0        1009  [Cloud, Mobile, Cognitive, Security, Research,...
1        1016                        [Healthcare, Biotechnology]
2        1028  [enterprise, software, applications, database,...
3        1033  [Management Consulting, Systems Integration an...
4        1035  [Business Software, Developer Tools, Home & Ed...

In [ ]:
import pandas as pd
# Start with companies_df and merge employee counts
companies_full_df = pd.merge(companies_df, employee_counts_df.drop(columns=['time_recorded']), on='company_id', how='left')
print("Shape after merging employee counts:", companies_full_df.shape)

# Merge aggregated company industries
companies_full_df = pd.merge(companies_full_df, company_industries_agg, on='company_id', how='left')
print("Shape after merging company industries:", companies_full_df.shape)

# Merge aggregated company specialities
companies_full_df = pd.merge(companies_full_df, company_specialities_agg, on='company_id', how='left')
print("Shape after merging company specialities:", companies_full_df.shape)

# Fill NaN for aggregated lists with empty lists
companies_full_df['company_industries'] = companies_full_df['company_industries'].apply(lambda x: x if isinstance(x, list) else [])
companies_full_df['company_specialities'] = companies_full_df['company_specialities'].apply(lambda x: x if isinstance(x, list) else [])

print("\nFinal companies_full_df with all company-related information:")
display(companies_full_df.head())
print("Final companies_full_df info:")
companies_full_df.info()
# Ensure companies_full_df is defined for final merge.

Shape after merging employee counts: (35786, 12)
Shape after merging company industries: (35786, 13)
Shape after merging company specialities: (35786, 14)

Final companies_full_df with all company-related information:

,company_id,name,description,company_size,state,country,city,zip_code,address,url,employee_count,follower_count,company_industries,company_specialities
0,1009,IBM,"At IBM, we do more than work. We create. We cr...",7.0,NY,US,"Armonk, New York",10504,International Business Machines Corp.,https://www.linkedin.com/company/ibm,314102,16253625,[IT Services and IT Consulting],"[Cloud, Mobile, Cognitive, Security, Research,..."
1,1009,IBM,"At IBM, we do more than work. We create. We cr...",7.0,NY,US,"Armonk, New York",10504,International Business Machines Corp.,https://www.linkedin.com/company/ibm,313142,16309464,[IT Services and IT Consulting],"[Cloud, Mobile, Cognitive, Security, Research,..."
2,1009,IBM,"At IBM, we do more than work. We create. We cr...",7.0,NY,US,"Armonk, New York",10504,International Business Machines Corp.,https://www.linkedin.com/company/ibm,313147,16309985,[IT Services and IT Consulting],"[Cloud, Mobile, Cognitive, Security, Research,..."
3,1009,IBM,"At IBM, we do more than work. We create. We cr...",7.0,NY,US,"Armonk, New York",10504,International Business Machines Corp.,https://www.linkedin.com/company/ibm,311223,16314846,[IT Services and IT Consulting],"[Cloud, Mobile, Cognitive, Security, Research,..."
4,1016,GE HealthCare,Every day millions of people feel the impact o...,7.0,0,US,Chicago,0,-,https://www.linkedin.com/company/gehealthcare,56873,2185368,[Hospitals and Health Care],"[Healthcare, Biotechnology]"

Final companies_full_df info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35786 entries, 0 to 35785
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   company_id            35786 non-null  int64
 1   name                  35786 non-null  object
 2   description           35786 non-null  object
 3   company_size          35786 non-null  float64
 4   state                 35786 non-null  object
 5   country               35786 non-null  object
 6   city                  35786 non-null  object
 7   zip_code              35786 non-null  object
 8   address               35786 non-null  object
 9   url                   35786 non-null  object
 10  employee_count        35786 non-null  int64
 11  follower_count        35786 non-null  int64
 12  company_industries    35786 non-null  object
 13  company_specialities  35786 non-null  object
dtypes: float64(1), int64(3), object(10)
memory usage: 3.8+ MB

### Merging Jobs and Companies into a Final Dataset

In [ ]:
import pandas as pd


if 'company_id' not in jobs_df.columns:
    print("Warning: 'company_id' column is missing in jobs_df. Adding a placeholder column with pd.NA.")
    jobs_df['company_id'] = pd.NA

jobs_df['company_id'] = jobs_df['company_id'].astype('Int64')

# Merge
final_jobs_companies_df = pd.merge(jobs_df, companies_full_df, on='company_id', how='left')

print("Shape of final_jobs_companies_df:", final_jobs_companies_df.shape)
display(final_jobs_companies_df.head())

print("Final jobs_companies_df info:")
final_jobs_companies_df.info()


print("\nMissing values in final_jobs_companies_df:")
display(final_jobs_companies_df.isnull().sum()[final_jobs_companies_df.isnull().sum() > 0])

Warning: 'company_id' column is missing in jobs_df. Adding a placeholder column with pd.NA.
Shape of final_jobs_companies_df: (128427, 24)

,job_id,industries,skills,max_salary,med_salary,min_salary,pay_period,currency,compensation_type,benefits,...,state,country,city,zip_code,address,url,employee_count,follower_count,company_industries,company_specialities
0,3884428798,[Book and Periodical Publishing],"[Marketing, Public Relations, Writing/Editing]",85000.0,20.0,62300.0,HOURLY,USD,BASE_SALARY,[],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,3887470552,[Chemical Manufacturing],[Administrative],25.0,25.0,23.0,HOURLY,USD,BASE_SALARY,[],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3884431523,[Mining],"[Management, Training]",120000.0,25.0,100000.0,YEARLY,USD,BASE_SALARY,"[Medical insurance, Vision insurance, Dental i...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3884911725,"[Biotechnology Research, Medical Equipment Man...","[General Business, Business Development, Sales]",200000.0,25.0,10000.0,YEARLY,USD,BASE_SALARY,[],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,3887473220,[Financial Services],[Project Management],35.0,25.0,33.0,HOURLY,USD,BASE_SALARY,[],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Final jobs_companies_df info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 128427 entries, 0 to 128426
Data columns (total 24 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   job_id                128427 non-null  int64
 1   industries            128427 non-null  object
 2   skills                128427 non-null  object
 3   max_salary            40785 non-null   float64
 4   med_salary            40785 non-null   float64
 5   min_salary            40785 non-null   float64
 6   pay_period            40785 non-null   object
 7   currency              40785 non-null   object
 8   compensation_type     40785 non-null   object
 9   benefits              128427 non-null  object
 10  company_id            0 non-null       Int64
 11  name                  0 non-null       object
 12  description           0 non-null       object
 13  company_size          0 non-null       float64
 14  state                 0 non-null       object
 15  country               0 non-null       object
 16  city                  0 non-null       object
 17  zip_code              0 non-null       object
 18  address               0 non-null       object
 19  url                   0 non-null       object
 20  employee_count        0 non-null       float64
 21  follower_count        0 non-null       float64
 22  company_industries    0 non-null       object
 23  company_specialities  0 non-null       object
dtypes: Int64(1), float64(6), int64(1), object(16)
memory usage: 23.6+ MB

Missing values in final_jobs_companies_df:

max_salary               87642
med_salary               87642
min_salary               87642
pay_period               87642
currency                 87642
compensation_type        87642
company_id              128427
name                    128427
description             128427
company_size            128427
state                   128427
country                 128427
city                    128427
zip_code                128427
address                 128427
url                     128427
employee_count          128427
follower_count          128427
company_industries      128427
company_specialities    128427
dtype: int64

In [ ]:
final_jobs_companies_df.isnull().sum()

job_id                       0
industries                   0
skills                       0
max_salary               87642
med_salary               87642
min_salary               87642
pay_period               87642
currency                 87642
compensation_type        87642
benefits                     0
company_id              128427
name                    128427
description             128427
company_size            128427
state                   128427
country                 128427
city                    128427
zip_code                128427
address                 128427
url                     128427
employee_count          128427
follower_count          128427
company_industries      128427
company_specialities    128427
dtype: int64

In [ ]:
import pandas as pd

final_jobs_companies_df[['job_id', 'industries', 'skills', 'max_salary', 'med_salary', 'min_salary', 'benefits']]

,job_id,industries,skills,max_salary,med_salary,min_salary,benefits
0,3884428798,[Book and Periodical Publishing],"[Marketing, Public Relations, Writing/Editing]",85000.0,20.0,62300.0,[]
1,3887470552,[Chemical Manufacturing],[Administrative],25.0,25.0,23.0,[]
2,3884431523,[Mining],"[Management, Training]",120000.0,25.0,100000.0,"[Medical insurance, Vision insurance, Dental i..."
3,3884911725,"[Biotechnology Research, Medical Equipment Man...","[General Business, Business Development, Sales]",200000.0,25.0,10000.0,[]
4,3887473220,[Financial Services],[Project Management],35.0,25.0,33.0,[]
...,...,...,...,...,...,...,...
128422,3906265021,[],[Other],NaN,NaN,NaN,[]
128423,3906266100,[],"[Education, Training]",NaN,NaN,NaN,[]
128424,3906260896,[],"[Management, Manufacturing]",NaN,NaN,NaN,[]
128425,3902876612,[],"[Research, Analyst, Information Technology]",NaN,NaN,NaN,[]
128426,3902880529,[],"[Management, Manufacturing]",NaN,NaN,NaN,[]